sonar.projectKey=tasklist-backend
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.token=sqp_05edbd6761e78fe465502c7604344ee4cdfd1226
